### PR TITLE
Feature/compile button plus toggle

### PR DESCRIPTION
**Pull request by BrahimS**
Migrate all the logics of the text editor to PageProductChild.vue and compile on switch.
See Demo :https://nextcloud.ditrit.io/index.php/s/LNrgfb3ygBjRnbY

TODO in the futur:
1 - Update to composition API
2 - Create a composable file with all the logics for text editor.

### CODE REVIEW

**Comment by Mari0nV** [comment]
I see a bug that I don't have in demo-4-july:

https://user-images.githubusercontent.com/23618241/177829175-1b5b4a3b-04fb-445d-8e88-57d1242ceb43.mp4

The aws instance is not saved neither in the Text view, neither in the Model 3D view

**Comment by BrahimS** [comment]
[demo](https://user-images.githubusercontent.com/7687826/177834061-50212532-bac6-4910-88d7-55c863737d3a.webm)

**Comment by Zorin95670** [comment]
> Video-Thu-Jul-07-2022-19-26-56.webm


@BrahimS  Why on this video we still have the compile button ?

**Review by Zorin95670 — CHANGES_REQUESTED** [review]
We still have the compile button

**Comment by BrahimS** [comment]
@Zorin95670 You can check this one without the compile button: Feature/compile on switch #196

**Pull request closed without merging**
